
export const getTransactionConfig = (key) => {
    const configs = {
        sales_invoices: {
            listUrl: '/transactions/sales/invoices',
            createUrl: '/transactions/sales/invoices',
            getOneUrl: (id) => `/transactions/${id}`,
            contactType: 'customers',
            clientLabelKey: 'sales.common.client',
            localePrefix: 'sales.invoices',
            noItemsKey: 'sales.invoices.no_invoices',
            startKey: 'sales.invoices.start_creating',
            addTitleKey: 'sales.invoices.add_invoice',
            editTitleKey: 'sales.invoices.edit_invoice',
            viewTitleKey: 'sales.invoices.view_invoice',
            filenamePrefix: 'Invoice',
            numberPlaceholderKey: 'sales.invoices.invoice_number_placeholder',
        },
        sales_returns: {
            listUrl: '/transactions/sales/returns',
            createUrl: '/transactions/sales/returns',
            getOneUrl: (id) => `/transactions/${id}`,
            contactType: 'customers',
            clientLabelKey: 'sales.common.client',
            localePrefix: 'sales.returns',
            noItemsKey: 'sales.returns.no_returns',
            startKey: 'sales.returns.start_returns',
            addTitleKey: 'sales.returns.add_return',
            editTitleKey: 'sales.returns.edit_return',
            viewTitleKey: 'sales.returns.view_return',
            filenamePrefix: 'Return',
            numberPlaceholderKey: 'sales.returns.return_number_placeholder',
        },
        sales_quotations: {
            listUrl: '/transactions/sales/quotations',
            createUrl: '/transactions/sales/quotations',
            getOneUrl: (id) => `/transactions/${id}`,
            contactType: 'customers',
            clientLabelKey: 'sales.common.client',
            localePrefix: 'sales.quotations',
            noItemsKey: 'sales.quotations.no_quotations',
            startKey: 'sales.quotations.start_quotations',
            addTitleKey: 'sales.quotations.add_quotation',
            editTitleKey: 'sales.quotations.edit_quotation',
            viewTitleKey: 'sales.quotations.view_quotation',
            filenamePrefix: 'Quotation',
            numberPlaceholderKey: 'sales.quotations.quotation_number_placeholder',
            hidePaymentDetails: true,
        },
        purchases_invoices: {
            listUrl: '/transactions/purchases/invoices',
            createUrl: '/transactions/purchases/invoices',
            getOneUrl: (id) => `/transactions/${id}`,
            contactType: 'suppliers',
            clientLabelKey: 'purchases.invoices.supplier',
            localePrefix: 'purchases.invoices',
            noItemsKey: 'purchases.invoices.no_invoices',
            startKey: 'purchases.invoices.start_creating',
            addTitleKey: 'purchases.invoices.add_invoice',
            editTitleKey: 'purchases.invoices.edit_invoice',
            viewTitleKey: 'purchases.invoices.view_invoice',
            filenamePrefix: 'PurchaseInvoice',
            numberPlaceholderKey: 'purchases.invoices.invoice_number_placeholder',
        },
        purchases_purchase_orders: {
            listUrl: '/transactions/purchases/purchaseOrder',
            createUrl: '/transactions/purchases/purchaseOrder',
            getOneUrl: (id) => `/transactions/${id}`,
            contactType: 'suppliers',
            clientLabelKey: 'purchases.invoices.supplier',
            localePrefix: 'purchases.purchase_orders',
            noItemsKey: 'purchases.purchase_orders.no_orders',
            startKey: 'purchases.purchase_orders.start_creating',
            addTitleKey: 'purchases.purchase_orders.add_order',
            editTitleKey: 'purchases.purchase_orders.edit_order',
            viewTitleKey: 'purchases.purchase_orders.view_order',
            filenamePrefix: 'PurchaseOrder',
            numberPlaceholderKey: 'purchases.purchase_orders.order_number_placeholder',
            hidePaymentDetails: true,
        },
        purchases_returns: {
            listUrl: '/transactions/purchases/returns',
            createUrl: '/transactions/purchases/returns',
            getOneUrl: (id) => `/transactions/${id}`,
            contactType: 'suppliers',
            clientLabelKey: 'purchases.invoices.supplier',
            localePrefix: 'purchases.returns',
            noItemsKey: 'purchases.returns.no_returns',
            startKey: 'purchases.returns.start_returns',
            addTitleKey: 'purchases.returns.add_return',
            editTitleKey: 'purchases.returns.edit_return',
            viewTitleKey: 'purchases.returns.view_return',
            filenamePrefix: 'PurchaseReturn',
            numberPlaceholderKey: 'purchases.returns.return_number_placeholder',
        },
        purchases_requests: {
            listUrl: '/transactions/purchases/requests',
            createUrl: '/transactions/purchases/requests',
            getOneUrl: (id) => `/transactions/${id}`,
            contactType: 'suppliers',
            clientLabelKey: 'purchases.invoices.supplier',
            localePrefix: 'purchases.requests',
            noItemsKey: 'purchases.requests.no_requests',
            startKey: 'purchases.requests.start_requests',
            addTitleKey: 'purchases.requests.add_request', // You might need to add this key to locales if missing
            editTitleKey: 'purchases.requests.edit_request', // You might need to add this key to locales if missing
            viewTitleKey: 'purchases.requests.view_request', // You might need to add this key to locales if missing
            filenamePrefix: 'PurchaseRequest',
            numberPlaceholderKey: 'purchases.requests.request_number_placeholder', // You might need to add this key to locales if missing
            hidePaymentDetails: true,
        },
    };
    return configs[key] || configs.sales_invoices;
};
